name = "MusicalPlaying"
uuid = "52cb4fde-ed05-4e62-916e-6df020caeb68"
authors = ["Thomas Poulsen <ta.poulsen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
MIDI = "f57c4921-e30c-5f49-b073-3f2f2ada663e"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"

[compat]
MIDI = "2.7.0"
WAV = "1.2.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
